# Form implementation generated from reading ui file 'src/UI/window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 643)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.live_stats_tab = QtWidgets.QWidget()
        self.live_stats_tab.setObjectName("live_stats_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.live_stats_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cpu_label = QtWidgets.QLabel(parent=self.live_stats_tab)
        self.cpu_label.setObjectName("cpu_label")
        self.horizontalLayout.addWidget(self.cpu_label)
        self.cpu_temp_label = QtWidgets.QLabel(parent=self.live_stats_tab)
        self.cpu_temp_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cpu_temp_label.setObjectName("cpu_temp_label")
        self.horizontalLayout.addWidget(self.cpu_temp_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.cpu_graph = PlotWidget(parent=self.live_stats_tab)
        self.cpu_graph.setObjectName("cpu_graph")
        self.verticalLayout.addWidget(self.cpu_graph)
        self.gpu_label = QtWidgets.QLabel(parent=self.live_stats_tab)
        self.gpu_label.setObjectName("gpu_label")
        self.verticalLayout.addWidget(self.gpu_label)
        self.gpu_graph = PlotWidget(parent=self.live_stats_tab)
        self.gpu_graph.setObjectName("gpu_graph")
        self.verticalLayout.addWidget(self.gpu_graph)
        self.ram_label = QtWidgets.QLabel(parent=self.live_stats_tab)
        self.ram_label.setObjectName("ram_label")
        self.verticalLayout.addWidget(self.ram_label)
        self.ram_graph = PlotWidget(parent=self.live_stats_tab)
        self.ram_graph.setObjectName("ram_graph")
        self.verticalLayout.addWidget(self.ram_graph)
        self.tabWidget.addTab(self.live_stats_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.curr_gov_combobox = QtWidgets.QComboBox(parent=self.settings_tab)
        self.curr_gov_combobox.setObjectName("curr_gov_combobox")
        self.verticalLayout_2.addWidget(self.curr_gov_combobox)
        self.clear_ram_btn = QtWidgets.QPushButton(parent=self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_ram_btn.sizePolicy().hasHeightForWidth())
        self.clear_ram_btn.setSizePolicy(sizePolicy)
        self.clear_ram_btn.setObjectName("clear_ram_btn")
        self.verticalLayout_2.addWidget(self.clear_ram_btn)
        self.tabWidget.addTab(self.settings_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cpu_label.setText(_translate("MainWindow", "CPU"))
        self.cpu_temp_label.setText(_translate("MainWindow", "loading..."))
        self.gpu_label.setText(_translate("MainWindow", "GPU"))
        self.ram_label.setText(_translate("MainWindow", "RAM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.live_stats_tab), _translate("MainWindow", "statistics"))
        self.clear_ram_btn.setText(_translate("MainWindow", "Clear RAM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "settings"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
